server:
  port: 28080

eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    status-page-url-path: /admin/info
    health-check-url-path: /admin/health
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/